### ISSUE TITLE
Recurring on the 31st, how is this handled for February for example?

### ISSUE THREAD

**Issue by akaalias** [jhubert/ruby-date-recur#1]
Not sure if this is actually a bug or just the way you want it to work. 

The problem I see is that when I create a recurring event on the 31st of a month (or the 30th, or 29th for that matter), the list of recurring dates in the future skips the months that don't have 31 days, such as February (see below)

Date.today.recur(:monthly,"1:0000000000000000000000000000001")

 [Thu, 15 Jul 2010, Sat, 31 Jul 2010, Tue, 31 Aug 2010, Sun, 31 Oct 2010, Fri, 31 Dec 2010, Mon, 31 Jan 2011, Thu, 31 Mar 2011, Tue, 31 May 2011]

Is there a way to do this using the library and/or am I missing a point here? 

Otherwise great library, thank you for adding support as a rails plugin, too!

Best, 

Alexis

**Comment by jhubert** [comment]
Hi Alexis, thanks for submitting this and I'm very sorry that its take. Me 2.5 years to respond. I haven't used github for issues until now. 

If this is still something that interests you, what do you think the behavior should be? It seems that the intention isn't to have something trigger on the 31st, but instead to trigger on the last day of the month, right? I would probably look to create an alternate syntax for that.
